package com.example.companyapp.model.employee;

public enum JobTitle {
    SPECJALISTA_DS_MARKTETINGU,
    KIEROWNIK_OBSLUGI_KLIENTA,
    ANALITYK_FINANSOWY,
    PROGRAMISTA_OPROGRAMOWANIA,
    KIEROWNIK_ZASOBOW_LUDZKICH,
    ANALITYK_BIZNESOWY,
    INZYNIER_DS_BEZPIECZENSTA_IT,
    ASYSTENS_ZARZADU,
    SPECJALISTA_DS_SPRZEDAZY,
    KIEROWNIK_PROJEKTU,
    DORADCA_FINANSOWY,
    SPECJALISTA_DS_HR
}
